### ISSUE TITLE
Error on plugin startup

### ISSUE THREAD

**Issue by gdavids57** [itavero/homebridge-apc-ups-alert#1]
Upon Homebridge startup and apc-ups-alert initialization, I receive a log entry, "Incorrect configuration: servers must be an array of servers and contain at least one server."  This error prevents homebridge from completing its startup sequence as it keeps restarting, trying to initialize the plug-in.  

**To Reproduce:**

Install the plug-in, as per the ReadMe information.  
Confirm the UPS is integrated with the server using apcaccess.
Confirm the NIS service is available by seeing --enable-net in the apcupsd configuration
Restart Homebridge and note the initilization error

**Expected behavior:**
I expect the plug-in to successfully initialize and monitor the ups

**Logs:**

```
[10/08/2022, 17:38:14] [apc-ups-alert] Incorrect configuration: servers must be an array of servers and contain at least one server.
[10/08/2022, 17:38:14] TypeError: x.servers is not iterable
    at isPluginConfiguration (/usr/local/lib/node_modules/homebridge-apc-ups-alert/src/configModels.ts:17:26)
    at new UpsAlertHomebridgePlatform (/usr/local/lib/node_modules/homebridge-apc-ups-alert/src/platform.ts:25:30)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:473:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:400:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:176:29)
```

**Plugin Config:**

```json
{
            "server": [
                {
                    "host": "homebridge-00.local",
                    "interval": 10
                }
            ],
            "defaults": {
                "interval": 60,
                "low_battery_threshold": 40
            },
            "platform": "apc-ups-alert"
        }
```

**Screenshots:**
N/A as the log entry completely represents the error

**Environment:**

* **Plugin Version**: v0.0.1 -beta.0
* **Homebridge Version**:  v1.5.0
* **Node.js Version**:  v16.13.2
* **NPM Version**:  v6.14.12
* **Operating System**:  Raspbian GNU/Unix Bullseye (11)

**Comment by gdavids57** [comment]
I noticed the plug-in is now at Beta-2 and I installed this version.  The plug-in now initialized but is getting an ECONNREFUSED error:
[06/09/2022, 17:44:21] [apc-ups-alert] Error while polling homebridge-00.local: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"xx.xx.xx.xx","port":3551}

I further confirmed NIS is listening by executing netstat -an and receiving:
tcp        0      0 127.0.0.1:3551          0.0.0.0:*               LISTEN

**Comment by gdavids57** [comment]
I determined the cause for the ECONNREFUSED error to be that I had the plug-in configured to connect to the server at homebridge-00.local which resolved to an address different than localhost (e.g., 127.0.0.1).  I made the incorrect assumption the NIS service was listening on both localhost and the server's network address.  Once I configured the plug-in to connect to localhost, the accessory came up; however, the code's use of a HAP leak detector triggered a warning the characteristics set by the plug-in did not match the standard characteristics for a leak detector but homekit registered them nonetheless.

**Comment by seanwalter** [comment]
I just got the same error after installing this plugin. The plugin populates the config.json file with a "server" block but appears to expect a "servers" block. I manually edited "server" in my config.json to say "servers" and now it works. This is the same "server" line that appears in OPs plugin config section above.
